<?php

/**
 * Created by PhpStorm.
 * User: Frost Wong <frostwong@gmail.com>
 * Date: 8/7/16
 * Time: 1:42 PM
 */
class BaseController extends Yaf\Controller_Abstract
{
    // todo check rules
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //todo check rules of input params
    }
}